version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - esnetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.1
        ports:
            - "5601:5601"
        networks:
            - esnetwork
        depends_on:
            - elasticsearch
volumes:
    esdata:
        driver: local
networks:
    esnetwork:
        driver: bridge